# Generated by Django 5.2.1 on 2025-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="generated_video_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
